# # collect interval
interval = 60

# Read metrics from one or many vCenters
[[instances]]
##  vCenter URLs to be monitored. These three lines must be uncommented
## and edited for the plugin to work.
vcenter = "https://172.24.98.200/sdk"
username = "administrator@vsphere.local"
password = "Iop[]=-09*"
## timeout applies to any of the api request made to vcenter
timeout = "60s"
labels = { "vcenter" = "172.24.98.200"  }
## Optional SSL Config
# use_tls = false
# tls_ca = "/path/to/cafile"
# tls_cert = "/path/to/certfile"
# tls_key = "/path/to/keyfile"
## Use SSL but skip chain & host verification
insecure_skip_verify = true

## The Historical Interval value must match EXACTLY the interval in the daily
# "Interval Duration" found on the VCenter server under Configure > General > Statistics > Statistic intervals
# historical_interval = "5m"
[kafka]
brokers = ["cdp01:9092", "cdp02:9092", "cdp03:9092"]
topic = "engine_source_topic"
required_acks = 1
timeout = "10s"